---
title: "structuurmetrieken westhoek"
author: "Yolan Bosteels"
date: "2025-04-25"
output: html_document
---

```{r}
wd <- ("C:/Users/yolan/OneDrive/Documenten/UGENT/Master/Stage/R/")
setwd(wd)
```
############
STATISTIEKEN
############
#Inladen van packages
```{r}
library(raster)
library(vegan)
library(spdep)
library(ape)


#functie voor berekenen shannon roughness
sh <- function(x,...){
  x = table(na.omit(as.vector(x)))
  return(diversity(x, index = "shannon"))
}

library(spdep)

library(spdep)

moran_i <- function(x, ...) {
  valid_values <- na.omit(x)
  # als er meer dan 5 in het totaal aantal van 25 cellen NA zijn wordt er geen Morans I berekend
  if (length(valid_values) < 5) {
    return(NA)
  }
  
  cell_size <- sqrt(length(x))
  coords <- expand.grid(1:cell_size, 1:cell_size)
  coords <- coords[!is.na(x), ]
  nb <- dnearneigh(coords, 0, 1.1)#angrenzende cellen worden gedefinieerd als cellen waarvan het celcentrum op maximaal 1m ligt van het centrum van een cel. 
  
  
  degrees <- card(nb)
  
  # Filter to only nodes with non-zero degree
  nonzero_degrees <- sum(degrees > 0)
  
  # Check if we have at least 20 conneted nodes
  if (nonzero_degrees < 20) {
    return(NA)
  }
  
  wts_listw <- nb2listw(nb, style = "B", zero.policy = TRUE)  # <<< HERE: allow zero neighbors
  x_valid <- as.vector(valid_values)
  moran <- Moran.I(x_valid, w = listw2mat(wts_listw), na.rm = TRUE, scaled = TRUE)
  
  return(moran$observed)
}




```

INLADEN RASTERS
```{r}
crss = " +proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=49.8333339 +lat_2=51.1666672333333 +x_0=150000.01256 +y_0=5400088.4378 +ellps=intl +units=m +no_defs  "

cell_size <- 5 #default celgroote voor dit project

chm_ras1 = raster('wh_vh1m.tif', crs = crss)
chm_ras1[chm_ras1 < 0] <- NA

chm_ras5 = aggregate(chm_ras1, fun = mean, fact = cell_size/res(chm_ras1))


classes_df = c(-Inf,1, 1,1,2,2,2,5,3,5,Inf,4)
classes_chm = matrix(classes_df,ncol = 3, byrow=T)
classes_df = c(-Inf, 0,1, 0, 0.25,2, 0.25,0.5,3, 0.5,0.75,4,0.75,1,5)


chm_clas5 = reclassify(chm_ras5, classes_chm)




```

Hier wordt de begrazingsdata ingeladen en geagregeerd tot op 25x25m. Een correcte filtering van deze data dient nog te gebeuren!!!

```{r}
load("C:/Users/yolan/Dropbox/pc/Downloads/data_westhoek (3).Rdata")

# Suppose your data is now in an object called 'gps_points' (adjust if needed)
# It should have columns X and Y
# Convert to SpatialPoints
data_westhoek$x <- as.numeric(as.character(data_westhoek$x))
data_westhoek$y <- as.numeric(as.character(data_westhoek$y))
coordinates(data_westhoek) <- ~x+y

proj4string(data_westhoek) <- CRS(crss)

# Load and prepare the CHM raster
chm_ras1 <- raster('wh_vh1m.tif', crs = crss)
chm_ras1[chm_ras1 < 0] <- NA

cell_size_begrazing <- 25
chm_ras5 <- aggregate(chm_ras1, fun = mean, fact = cell_size_begrazing / res(chm_ras1)[1])

# Create an empty raster based on chm_ras5
count_raster <- raster(chm_ras5)
values(count_raster) <- 0

# Count points per cell
# First extract the cell number for each point
cells <- cellFromXY(count_raster, data_westhoek)

# Then tabulate counts
tab <- table(cells)

# Assign counts to raster
count_raster[as.numeric(names(tab))] <- as.numeric(tab)

# Plot
plot(count_raster, main = "Point Density Heatmap begrazing")


writeRaster(count_raster, 
            filename = paste0(output_folder, "grazing_density.tif"), 
            format = "GTiff", 
            overwrite = TRUE)
```

MEAN HEIGHT
```{r}
chm_mean_f = aggregate(chm_ras1, fun = mean, fact = cell_size/res(chm_ras1))

chm_min_f = aggregate(chm_ras1, fun = min, fact = cell_size/res(chm_ras1))

#chm_max_f = aggregate(chm_ras1, fun = max, fact = cell_size/res(chm_ras1))

```

ROUGHNESS
```{r}
#Verticale heterogeniteit via Variantie AGGREGATED 0.25x0.25
chm_var = aggregate(chm_ras1, fact = cell_size/res(chm_ras1), fun = sd, na.rm = T)

```

DISTRIBUTION
```{r}
#Verticale heterogeniteit via Variantie AGGREGATED 0.25x0.25
chm_fish = aggregate(chm_ras1, fact = cell_size/res(chm_ras1), fun = skewness, na.rm = T) 

```

MORAN
```{r}
#Horizontale heterogeniteit via Morans I MOVING WINDOW
#omdat morans I wat meer moeite heeft met NO data values gaan we hier wat minder streng zijn rond NA waardes toekennen. Daarom laden we terug het originele bestand in. (chm_ras1_moran). Ook zal de warning subgraphs verschijnen. Dit gebeurt voor 5 cellen in het raster. Concreet wil dat zeggen dat er één of meerdere cellen geisoleerd zijn geraakt en dus geen buren hebben. De grootste cluster verbonden cellen wordt behouden en wordt gebruikt voor morans i. 
chm_ras1_moran = raster('wh_vh1m.tif', crs = crss)
chm_locm_ras = aggregate(chm_ras1_moran, fun = moran_i, fact = 10/res(chm_ras1))

```
```{r}
plot(chm_locm_ras)
```

SHANNON
```{r}
#Verticale heterogeniteit via Shannon
classes_df = c(-Inf,0.5, 1,0.5,2,3,2,Inf,3)
classes_chm = matrix(classes_df,ncol = 3, byrow=T)
chm_clas1 = reclassify(chm_ras1, classes_chm)
chm_H_class = aggregate(chm_clas1, fact = cell_size/res(chm_clas1), sh)
```



WRITE RASTERS
```{r}
folder = "C:/Users/yolan/OneDrive/Documenten/UGENT/Master/Stage/hoogtemetrieken/"


writeRaster(chm_H_class, 
            filename = paste0(folder, "chm_shannon.tif"), 
            format = "GTiff", 
            overwrite = TRUE)

writeRaster(chm_mean_f, 
            filename = paste0(folder, "chm_mean.tif"), 
            format = "GTiff", 
            overwrite = TRUE)

writeRaster(chm_locm_ras, 
            filename = paste0(folder, "chm_localmoran.tif"), 
            format = "GTiff", 
            overwrite = TRUE)

writeRaster(chm_fish, 
            filename = paste0(folder, "chm_fisher.tif"), 
            format = "GTiff", 
            overwrite = TRUE)

writeRaster(chm_max_f, 
            filename = paste0(folder, "chm_max.tif"), 
            format = "GTiff", 
            overwrite = TRUE)

writeRaster(chm_min_f, 
            filename = paste0(folder, "chm_min.tif"), 
            format = "GTiff", 
            overwrite = TRUE)
writeRaster(count_raster, 
            filename = paste0(folder, "grazing_density.tif"), 
            format = "GTiff", 
            overwrite = TRUE)
```

